### ISSUE TITLE
Update to Cluster-api v1alpha2

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/wksctl#85]
Need to migrate to using cluster-api v1alpha2.

**Comment by youyongsong** [comment]
Hello, cluster-api v1alpha2 introduced bootstrap provider(default implementation is [cluster-api-bootstrap-provider-kubeadm](https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm)). But this mechanism seems useless to `wksctl`, because `wksctl` already has `SetupNodePlan` doing the same thing and is better than bootstrap provider's cloud-init script. I wonder how will `wksctl` handle the bootstrap provider mechanism when migrating to cluster-api v1alpha2 ?

**Comment by luxas** [comment]
Closing in favor of #170

**Comment by luxas** [comment]
Hi @youyongsong, we will investigate integrating with the kubeadm bootstrap provider. I created a new dedicated issue for this: #212
